### ISSUE TITLE
asking for question

### ISSUE THREAD

**Issue by huanming370** [yyyx-not-found/CS61a#1]
I‘ve searched for the code of cs61a, and I found you. I want to ask a question that has puzzled me for two days. It's from the hog-question7-suite2-case3, you can see the image. I want to know the correct answer, and if I can't pass the question I won't able to unlock the rest of cs61a.
![image](https://user-images.githubusercontent.com/62684142/182006355-8964dcf2-766d-4242-a72f-cd40ffa7ab5e.png)

**Comment by yyyx-not-found** [comment]
Hi, here is the answer!
```python
>>> from hog import play, always_roll, announce_lead_changes
>>> from dice import make_test_dice
>>> def count(n):
...     def say(s0, s1, curr_count=None):
...         if curr_count is None:
...           curr_count = n
...         return curr_count + 1, str(curr_count) + " " + str(s0)
...     return say
>>> s0, s1 = play(always_roll(1), always_roll(1), dice=make_test_dice(5), goal=15, say=count(1))
(line 1)? 1 7
(line 2)? 2 7
(line 3)? 3 12
(line 4)? 4 12
(line 5)? 5 19
-- OK! --
```
Recall that **Pigs on Prime** increase a prime score to the next prime score. At the first turn, player 0 rolls one dice and get **5** points, and he/she actually gains **7** points due to Pigs on Prime!! And one more thing worth noting is that this function will only output the score for player 0.
Good luck with your coding :)

**Comment by huanming370** [comment]
> Hi, here is the answer!
> 
> ```python
> >>> from hog import play, always_roll, announce_lead_changes
> >>> from dice import make_test_dice
> >>> def count(n):
> ...     def say(s0, s1, curr_count=None):
> ...         if curr_count is None:
> ...           curr_count = n
> ...         return curr_count + 1, str(curr_count) + " " + str(s0)
> ...     return say
> >>> s0, s1 = play(always_roll(1), always_roll(1), dice=make_test_dice(5), goal=15, say=count(1))
> (line 1)? 1 7
> (line 2)? 2 7
> (line 3)? 3 12
> (line 4)? 4 12
> (line 5)? 5 19
> -- OK! --
> ```
> 
> Recall that **Pigs on Prime** increase a prime score to the next prime score. At the first turn, player 0 rolls one dice and get **5** points, and he/she actually gains **7** points due to Pigs on Prime!! And one more thing worth noting is that this function will only output the score for player 0. Good luck with your coding :)

Thanks for the reply! 
Actually I think it was "_return curr_count+1, str(curr_count) + " " + str(s0)_" confused me. I thought it would return _curr_count+1_ and a str. Anyway, I'm going to strengthen the practice, thanks again!!
